// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaoDimas.Infraestrutura.Persistencia;

#nullable disable

namespace SaoDimas.Infraestrutura.Persistencia.Migrations
{
    [DbContext(typeof(SaoDimasDbContext))]
    partial class SaoDimasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SaoDimas.Dominio.Entities.Comunidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("OrdemExibicao");

                    b.HasIndex("Tipo")
                        .IsUnique()
                        .HasDatabaseName("UX_Comunidades_MatrizUnica")
                        .HasFilter("[Tipo] = 1");

                    b.ToTable("Comunidades", null, t =>
                        {
                            t.HasCheckConstraint("CK_Comunidades_OrdemExibicao", "[OrdemExibicao] >= 0");

                            t.HasCheckConstraint("CK_Comunidades_Tipo", "[Tipo] IN (1, 2)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = true,
                            CriadoEm = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Paróquia São Dimas",
                            OrdemExibicao = 1,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativa = true,
                            CriadoEm = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Santa Teresinha",
                            OrdemExibicao = 2,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 3,
                            Ativa = true,
                            CriadoEm = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Santo Inácio",
                            OrdemExibicao = 3,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 4,
                            Ativa = true,
                            CriadoEm = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Santo Expedito",
                            OrdemExibicao = 4,
                            Tipo = 2
                        });
                });

            modelBuilder.Entity("SaoDimas.Dominio.Entities.Dizimista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<int>("ComunidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .IsFixedLength();

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DataEntrada")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Endereco")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .UseCollation("Latin1_General_100_CI_AI");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("[Cpf] IS NOT NULL");

                    b.HasIndex("Nome");

                    b.HasIndex("ComunidadeId", "Nome");

                    b.ToTable("Dizimistas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Dizimistas_Status", "[Status] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("SaoDimas.Dominio.Entities.Dizimista", b =>
                {
                    b.HasOne("SaoDimas.Dominio.Entities.Comunidade", null)
                        .WithMany()
                        .HasForeignKey("ComunidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
